### ISSUE TITLE
Wrong rotation for animated objects

### ISSUE THREAD

**Issue by zenyaz** [0xafbf/blender-datasmith-export#47] opened 2020-12-28 14:56 UTC
I have 2 types of objects 
1. Air balloon static (internal Blender rotation is 90;0;0)
2. Air balloon animated (internal Blender rotation is 90;0;0  and some XYZ-changing).
All animations are baked frame by frame in blender.

After export to Datasmith i have following scene:
- All balloons placed correctly XYZ
- Static balloons has proper rotation
- Dynamic balloons has proper animation XYZ, but WRONG rotation instead "90;0;0" they have "-90;0;0", so looks like upside down.

I opened **anim_new.json** and noticed that rotation coded wrong. When i changed in json file automatically "-90"->"90" for all keyframes, then UE plays everything correctly.

**Comment by RumbleballTheReal** [comment] 2021-05-03 11:22
The problem is a missing minus in the x rotation. Just fixed it for our artists.
Open the plugin folder, open export_datasmith.py with a text editor, search for
`rot_fix = np.array((to_deg, -to_deg, to_deg))`
and change it to
`rot_fix = np.array((-to_deg, -to_deg, to_deg))`
save the file. Restart Blender

**Comment by 0xafbf** [comment] 2021-05-22 16:22
Hello guys! sorry for the delay!
Thanks zenyaz for spotting the issue and thanks @RumbleballTheReal for proposing the fix.
I will integrate it because I have seen it is also affecting other people.

**Comment by 0xafbf** [comment] 2021-05-22 21:42
Just commited the fix you proposed, so i'm closing this for now.

**Closed by 0xafbf** 2021-05-22 21:42 UTC
